[package]
name = "webtui-wasm-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11.0"
web-sys = { version = "0.3.83", features = ["Attr"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
#yew-attrs = "0.2.4"

[profile.release]
opt-level = "s"
lto = true
